Add burn type artifact
maphe/maphe.github.io pull request #162
Opened 2022-04-15 08:53 UTC by Junlol

Hi maphe,

I want to know how much damage Hwayoung can do with the burn artifact. 
For example, use Junkyard Dog or Indestructible Gaiters.

So I try to add the burn artifact, when Hwayoung is matched with the burn artifact, so that Hwayoung can have dot.burn to show the burn damage.

If you also think this is a good idea, welcome to merge this request, or close it anytime.

2022-04-15 14:53 UTC, maphe requested changes
Hey thanks for taking the time, I think it's a good idea to add, if you needed it there's probably other people that can benefit from it. I'd just make it more generic to support other types of DoT while we're at it. Then if you feel like it feel free to add Torn Sleeve and the Summer Iseria one.

2022-04-15 14:53 UTC, maphe commented on e7-damage-calc/artifacts.js
> +  burn: 'burn'
let's make this one dot so we can re-use with bleed and bomb

```suggestion
  dot: 'dot'
```

2022-04-15 14:53 UTC, maphe commented on e7-damage-calc/artifacts.js
> +    type: artifactDmgType.burn,
so this would become
```suggestion
    type: artifactDmgType.dot,
    dot: [dot.burn],
```

2022-04-15 14:53 UTC, maphe commented on e7-damage-calc/calculator.js
> +    }
this you can then just one line above

```
this.dot = [...(heroes[id].dot || []), ...(artifact?.getDoT() || [])];
```

and you'll need to add the `addDoT` function in the `Artifact` class, that should be fairly easy

2022-04-18 05:19 UTC, Junlol commented
Great idea, i'm done.

2022-04-18 05:38 UTC, maphe approved these changes

2022-04-18 05:38 UTC, merged